spring:
  application:
    name: BOOKS-CONSUMER
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true

server:
  port: 8090

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 10000